-- MySQL Script generated by MySQL Workbench
-- 12/22/16 12:44:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema restoran
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restoran
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restoran` DEFAULT CHARACTER SET utf8 ;
USE `restoran` ;

-- -----------------------------------------------------
-- Table `restoran`.`makanan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restoran`.`makanan` (
  `id_makanan` INT NOT NULL,
  `nama_makanan` VARCHAR(100) NULL,
  `harga_makanan` INT NULL,
  `kategori_makanan` VARCHAR(100) NULL,
  PRIMARY KEY (`id_makanan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restoran`.`minuman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restoran`.`minuman` (
  `id_minuman` INT NOT NULL,
  `nama_minuman` VARCHAR(100) NULL,
  `harga_minuman` INT NULL,
  `kategori_minuman` VARCHAR(100) NULL,
  PRIMARY KEY (`id_minuman`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restoran`.`pembayaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restoran`.`pembayaran` (
  `id_transaksi` INT NOT NULL,
  `tanggal_transaksi` DATE NULL,
  `total_bayar` INT NULL,
  PRIMARY KEY (`id_transaksi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restoran`.`meja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restoran`.`meja` (
  `id_meja` VARCHAR(10) NOT NULL,
  `nama_meja` VARCHAR(45) NULL,
  PRIMARY KEY (`id_meja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restoran`.`detail_pembayaran_makanan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restoran`.`detail_pembayaran_makanan` (
  `id_transaksi` INT NOT NULL,
  `id_makanan` INT NOT NULL,
  `jumlah_makanan` INT NULL,
  PRIMARY KEY (`id_transaksi`, `id_makanan`),
  INDEX `fk_pembayaran_has_makanan_makanan1_idx` (`id_makanan` ASC),
  INDEX `fk_pembayaran_has_makanan_pembayaran_idx` (`id_transaksi` ASC),
  CONSTRAINT `fk_pembayaran_has_makanan_pembayaran`
    FOREIGN KEY (`id_transaksi`)
    REFERENCES `restoran`.`pembayaran` (`id_transaksi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pembayaran_has_makanan_makanan1`
    FOREIGN KEY (`id_makanan`)
    REFERENCES `restoran`.`makanan` (`id_makanan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restoran`.`detail_pembayaran_minuman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restoran`.`detail_pembayaran_minuman` (
  `id_transaksi` INT NOT NULL,
  `id_minuman` INT NOT NULL,
  `jumlah_minuman` INT NULL,
  PRIMARY KEY (`id_transaksi`, `id_minuman`),
  INDEX `fk_pembayaran_has_minuman_minuman1_idx` (`id_minuman` ASC),
  INDEX `fk_pembayaran_has_minuman_pembayaran1_idx` (`id_transaksi` ASC),
  CONSTRAINT `fk_pembayaran_has_minuman_pembayaran1`
    FOREIGN KEY (`id_transaksi`)
    REFERENCES `restoran`.`pembayaran` (`id_transaksi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pembayaran_has_minuman_minuman1`
    FOREIGN KEY (`id_minuman`)
    REFERENCES `restoran`.`minuman` (`id_minuman`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restoran`.`detail_meja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restoran`.`detail_meja` (
  `id_transaksi` INT NOT NULL,
  `id_meja` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_transaksi`, `id_meja`),
  INDEX `fk_pembayaran_has_meja_meja1_idx` (`id_meja` ASC),
  INDEX `fk_pembayaran_has_meja_pembayaran1_idx` (`id_transaksi` ASC),
  CONSTRAINT `fk_pembayaran_has_meja_pembayaran1`
    FOREIGN KEY (`id_transaksi`)
    REFERENCES `restoran`.`pembayaran` (`id_transaksi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pembayaran_has_meja_meja1`
    FOREIGN KEY (`id_meja`)
    REFERENCES `restoran`.`meja` (`id_meja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
